### ISSUE TITLE
In certain environments, VIEWs not created with MySQL Percona

### ISSUE THREAD

**Issue by ChefMC** [A248/LibertyBans#231] opened 2023-09-03 00:09 UTC
### LibertyBans Version

LibertyBans_Release-1.1.0-M3

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Velocity

### Description

I installed the plugin on Velocity and after joining server I getting this in console:
https://pastebin.com/kCTntbvx

**Comment by A248** [comment] 2023-09-03 14:05
I can't reproduce this at all. I'll need further information to help you here.

You configured LibertyBans to use MariaDB, so please show me the tables in your database -- running `SHOW TABLES` will do. Please also send me your MariaDB version and the full server log since startup. And if you still have it, send the server log from when you first ran LibertyBans on MariaDB, since that is when tables are created.

**Comment by A248** [comment] 2023-09-03 18:58
Yes, you are using MySQL. I can see that `libertybans_applicable_bans` does not appear in your tables even after recreating them. Importantly, `libertybans_applicable_bans` is a VIEW, and not a TABLE.

This may be an issue related to MySQL Percona not allowing us to create VIEWs. We have automated tests which run and succeed on Oracle MySQL 8.0, including for table creation and query execution. I'm not sure why MySQL Percona would cause this issue, but I will work to perform additional testing until I can replicate it myself, including installing Percona.

> Log after deleting all tables:
> https://pastebin.com/ex1kiTDQ
All of the table and view creation queries succeeded according to this log. However, as you've mentioned, the VIEWs still do not exist.

**Comment by A248** [comment] 2023-09-03 19:01
I also noticed you have LimboAPI installed. We've had compatibility issues with LimboAuth before related to the database driver. If you have **LimboAuth** installed, please try without it.

**Comment by A248** [comment] 2023-09-04 02:33
I have verified this is not a problem with Percona. The automated test suite ran successfully -- which tested every single feature in LibertyBans with the MySQL Percona database. Additionally, I performed manual testing in my local environment. In both cases I used Docker with Percona 8.0.33-25, Release 25, Revision ff45844b, a slightly different Revision than yours but the same release otherwise.

Evidence suggests an issue with your particular environment or configuration. I can suggest again that you try without LimboAuth installed, if you're using that plugin. Ultimately, I will need more information to debug this problem.

**Comment by A248** [comment] 2023-10-02 19:10
Hi, @ChefMC , have you obtained any more information on this issue? I'm completely unable to reproduce it when I create a Percona server on my computer and run LibertyBans on it. As mentioned, this suggests there may be something wrong with your environment or configuration. We try to make LibertyBans work in all supported environments, however, so if there's anything you've found out or can report, please mention it.

**Comment by A248** [comment] 2024-01-15 14:42
Closing due to insufficient information to reproduce.

**Closed by A248** 2024-01-15 14:42 UTC
Labels: cannot-reproduce, bug
