### ISSUE TITLE
[Bug Report]: Not starting on PaperMC 1.20.1 / Build 40, 42+ (latest known to work: 39 and 41)

### ISSUE THREAD

**Issue by Athar42** [A248/LibertyBans#219] opened 2023-06-20 20:51 UTC
### LibertyBans Version

1.1.0 Snapshot Build 126 on Jenkins

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Spigot/Paper

### Description

Hi,

I will keep it simple : Not working on PaperMC 1.20.1-43, the plugin can't be initialized on startup.

I tried to catch the issue, but I'm not that good :')

Also tested on a fresh install, this is the only plugin added there, log below : 

Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.7+7) Host: Linux 5.10.0-23-amd64 (amd64)
Loading libraries, please wait...
[22:45:40 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:45:41 INFO]: Loaded 7 recipes
[22:45:42 INFO]: Starting minecraft server version 1.20.1
[22:45:42 INFO]: Loading properties
[22:45:42 INFO]: This server is running Paper version git-Paper-43 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3756f5b)
[22:45:42 INFO]: Server Ping Player Sample Count: 12
[22:45:42 INFO]: Using 4 threads for Netty based IO
[22:45:42 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[22:45:42 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 2 worker threads, and gen parallelism of 2 threads
[22:45:43 INFO]: Default game type: SURVIVAL
[22:45:43 INFO]: Generating keypair
[22:45:43 INFO]: Starting Minecraft server on 0.0.0.0:27000
[22:45:43 INFO]: Using epoll channel type
[22:45:43 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[22:45:43 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[22:45:43 INFO]: [LibertyBans] Loading server plugin LibertyBans v1.1.0-SNAPSHOT-2023-06-16T16:27:42Z
[22:45:43 INFO]: Server permissions file permissions.yml is empty, ignoring it
[22:45:43 INFO]: Preparing level "world"
[22:45:43 INFO]: Preparing start region for dimension minecraft:overworld
[22:45:44 INFO]: Time elapsed: 308 ms
[22:45:44 INFO]: Preparing start region for dimension minecraft:the_nether
[22:45:44 INFO]: Time elapsed: 130 ms
[22:45:44 INFO]: Preparing start region for dimension minecraft:the_end
[22:45:44 INFO]: Time elapsed: 65 ms
[22:45:44 INFO]: [LibertyBans] Enabling LibertyBans v1.1.0-SNAPSHOT-2023-06-16T16:27:42Z
[22:45:45 INFO]: [LibertyBans] No addons detected
[22:45:45 INFO]: [space.arim.libertybans.core.addon.AddonLoader] No addons loaded
[22:45:45 INFO]: [space.arim.libertybans.core.AbstractBaseFoundation] Conducting start phase...
[22:45:45 ERROR]: Error occurred while enabling LibertyBans v1.1.0-SNAPSHOT-2023-06-16T16:27:42Z (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.Server.isGlobalTickThread()'
        at space.arim.morepaperlib.scheduling.GracefulScheduling.isOnGlobalRegionThread(GracefulScheduling.java:146) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.isPrimaryThread0(BukkitFactoryOfTheFutureImpl.java:59) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.concurrent.MainThreadCachingFutureFactory.isPrimaryThread(MainThreadCachingFutureFactory.java:49) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.create(BukkitFactoryOfTheFutureImpl.java:53) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:56) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:45) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitPlatformHandleImpl.createFuturesFactory(BukkitPlatformHandle.java:61) ~[LibertyBans-ClassLoader:?]
        at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
        at space.arim.libertybans.core.service.StandardAsynchronicityManager.startup(StandardAsynchronicityManager.java:90) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.LifecycleGodfather.startup0(LifecycleGodfather.java:75) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.timedEvent(AbstractBaseFoundation.java:126) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.startup(AbstractBaseFoundation.java:64) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.env.spigot.plugin.SpigotPlugin.initialize(SpigotPlugin.java:116) ~[LibertyBans_1.1.0-SNAPSHOT.jar:?]
        at space.arim.libertybans.env.spigot.plugin.SpigotPlugin.onEnable(SpigotPlugin.java:48) ~[LibertyBans_1.1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-43]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:45:45 INFO]: [LibertyBans] Disabling LibertyBans v1.1.0-SNAPSHOT-2023-06-16T16:27:42Z
[22:45:45 WARN]: [LibertyBans] LibertyBans wasn't launched; check your log for a startup error
[22:45:45 INFO]: Running delayed init tasks
[22:45:45 INFO]: Done (3.064s)! For help, type "help"
container@pterodactyl~ Server marked as running...
[22:45:45 INFO]: Timings Reset

**Comment by Athar42** [comment] 2023-06-20 20:58
To add some more clues : Tested with PaperMC 1.20-17, it's working, no errors spotted, so that's something new with the latest updates.

**Comment by Athar42** [comment] 2023-06-20 21:15
A good, and a bad news, all in one (yeah, I'm doing some tests, trying to tacle down when this issue appeared).

Latest known good versions of PaperMC where this build is working : 1.20.1 Build 39 and 41 (revert changes from build 40)
Issue started since 1.20.1 Build 40 and then 42


Server build 39 : 
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.7+7) Host: Linux 5.10.0-23-amd64 (amd64)
Loading libraries, please wait...
[23:07:37 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:07:39 INFO]: Loaded 7 recipes
[23:07:39 INFO]: Starting minecraft server version 1.20.1
[23:07:39 INFO]: Loading properties
[23:07:39 INFO]: This server is running Paper version git-Paper-39 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 976b95c)
[23:07:39 INFO]: Server Ping Player Sample Count: 12
[23:07:39 INFO]: Using 4 threads for Netty based IO
[23:07:39 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[23:07:39 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 2 worker threads, and gen parallelism of 2 threads
[23:07:40 INFO]: Default game type: SURVIVAL
[23:07:40 INFO]: Generating keypair
[23:07:40 INFO]: Starting Minecraft server on 0.0.0.0:27000
[23:07:40 INFO]: Using epoll channel type
[23:07:40 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[23:07:40 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[23:07:40 INFO]: [LibertyBans] Loading server plugin LibertyBans v1.1.0-SNAPSHOT-2023-06-16T16:27:42Z
[23:07:40 INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:07:40 INFO]: Preparing level "world"
[23:07:41 INFO]: Preparing start region for dimension minecraft:overworld
[23:07:41 INFO]: Time elapsed: 273 ms
[23:07:41 INFO]: Preparing start region for dimension minecraft:the_nether
[23:07:41 INFO]: Time elapsed: 41 ms
[23:07:41 INFO]: Preparing start region for dimension minecraft:the_end
[23:07:41 INFO]: Time elapsed: 42 ms
[23:07:41 INFO]: [LibertyBans] Enabling LibertyBans v1.1.0-SNAPSHOT-2023-06-16T16:27:42Z
[23:07:41 INFO]: [LibertyBans] No addons detected
[23:07:41 INFO]: [space.arim.libertybans.core.addon.AddonLoader] No addons loaded
[23:07:42 INFO]: [space.arim.libertybans.core.AbstractBaseFoundation] Conducting start phase...
[23:07:42 INFO]: [com.zaxxer.hikari.HikariDataSource] LibertyBansPool-HyperSQL - Starting...
[23:07:43 INFO]: [com.zaxxer.hikari.pool.PoolBase] LibertyBansPool-HyperSQL - Driver does not support get/set network timeout for connections. (feature not supported)
[23:07:43 INFO]: [com.zaxxer.hikari.pool.HikariPool] LibertyBansPool-HyperSQL - Added connection org.hsqldb.jdbc.JDBCConnection@6a06677c
[23:07:43 INFO]: [com.zaxxer.hikari.HikariDataSource] LibertyBansPool-HyperSQL - Start completed.
[23:07:43 INFO]: [org.flywaydb.core.internal.license.VersionPrinter] Flyway Community Edition 8.2.0 by Redgate
[23:07:43 INFO]: [org.flywaydb.core.internal.database.base.BaseDatabaseType] Database: jdbc:hsqldb:file:/home/container/plugins/LibertyBans/internal/hypersql/punishments-database;sql.enforce_types=true;sql.enforce_names=true;hsqldb.default_table_type=cached;sql.sys_index_names=true;sql.restrict_exec=true;sql.enforce_refs=true;hsqldb.tx_interrupt_rollback=true (HSQL Database Engine 2.7)
[23:07:43 WARN]: [org.flywaydb.core.internal.database.base.Database] Flyway upgrade recommended: HSQLDB 2.7 is newer than this version of Flyway and support has not been tested. The latest supported version of HSQLDB is 2.6.
[23:07:43 INFO]: [org.flywaydb.core.internal.command.DbValidate] Successfully validated 9 migrations (execution time 00:00.083s)
[23:07:43 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Current version of schema "PUBLIC": 28
[23:07:43 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Schema "PUBLIC" is up to date. No migration necessary.
[23:07:44 INFO]: [space.arim.libertybans.core.AbstractBaseFoundation] Finished start phase in 1.789 seconds
[23:07:44 INFO]: Running delayed init tasks
[23:07:44 INFO]: Done (4.634s)! For help, type "help"
container@pterodactyl~ Server marked as running...
[23:07:44 INFO]: Timings Reset
[23:07:44 INFO]: [space.arim.libertybans.core.database.jooq.JooqClassloading] Finished pre-initializing classes in 0.93 seconds




And Server build 40 : 

Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.7+7) Host: Linux 5.10.0-23-amd64 (amd64)
Loading libraries, please wait...
[23:09:52 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:09:54 INFO]: Loaded 7 recipes
[23:09:54 INFO]: Starting minecraft server version 1.20.1
[23:09:54 INFO]: Loading properties
[23:09:54 INFO]: This server is running Paper version git-Paper-40 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: d6d4c78)
[23:09:54 INFO]: Server Ping Player Sample Count: 12
[23:09:54 INFO]: Using 4 threads for Netty based IO
[23:09:54 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[23:09:55 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 2 worker threads, and gen parallelism of 2 threads
[23:09:55 INFO]: Default game type: SURVIVAL
[23:09:55 INFO]: Generating keypair
[23:09:55 INFO]: Starting Minecraft server on 0.0.0.0:27000
[23:09:55 INFO]: Using epoll channel type
[23:09:55 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[23:09:55 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[23:09:55 INFO]: [LibertyBans] Loading server plugin LibertyBans v1.1.0-SNAPSHOT-2023-06-16T16:27:42Z
[23:09:55 INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:09:55 INFO]: Preparing level "world"
[23:09:56 INFO]: Preparing start region for dimension minecraft:overworld
[23:09:56 INFO]: Time elapsed: 487 ms
[23:09:56 INFO]: Preparing start region for dimension minecraft:the_nether
[23:09:56 INFO]: Time elapsed: 281 ms
[23:09:56 INFO]: Preparing start region for dimension minecraft:the_end
[23:09:57 INFO]: Time elapsed: 216 ms
[23:09:57 INFO]: [LibertyBans] Enabling LibertyBans v1.1.0-SNAPSHOT-2023-06-16T16:27:42Z
[23:09:57 INFO]: [LibertyBans] No addons detected
[23:09:57 INFO]: [space.arim.libertybans.core.addon.AddonLoader] No addons loaded
[23:09:57 INFO]: [space.arim.libertybans.core.AbstractBaseFoundation] Conducting start phase...
[23:09:57 ERROR]: Error occurred while enabling LibertyBans v1.1.0-SNAPSHOT-2023-06-16T16:27:42Z (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.Server.isGlobalTickThread()'
        at space.arim.morepaperlib.scheduling.GracefulScheduling.isOnGlobalRegionThread(GracefulScheduling.java:146) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.isPrimaryThread0(BukkitFactoryOfTheFutureImpl.java:59) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.concurrent.MainThreadCachingFutureFactory.isPrimaryThread(MainThreadCachingFutureFactory.java:49) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.create(BukkitFactoryOfTheFutureImpl.java:53) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:56) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:45) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitPlatformHandleImpl.createFuturesFactory(BukkitPlatformHandle.java:61) ~[LibertyBans-ClassLoader:?]
        at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
        at space.arim.libertybans.core.service.StandardAsynchronicityManager.startup(StandardAsynchronicityManager.java:90) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.LifecycleGodfather.startup0(LifecycleGodfather.java:75) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.timedEvent(AbstractBaseFoundation.java:126) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.startup(AbstractBaseFoundation.java:64) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.env.spigot.plugin.SpigotPlugin.initialize(SpigotPlugin.java:116) ~[LibertyBans_1.1.0-SNAPSHOT.jar:?]
        at space.arim.libertybans.env.spigot.plugin.SpigotPlugin.onEnable(SpigotPlugin.java:48) ~[LibertyBans_1.1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-40]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-40]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-40]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-40]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-40]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-40]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-40]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-40]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-40]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:09:57 INFO]: [LibertyBans] Disabling LibertyBans v1.1.0-SNAPSHOT-2023-06-16T16:27:42Z
[23:09:57 WARN]: [LibertyBans] LibertyBans wasn't launched; check your log for a startup error
[23:09:57 INFO]: Running delayed init tasks
[23:09:57 INFO]: Done (3.094s)! For help, type "help"
container@pterodactyl~ Server marked as running...
[23:09:57 INFO]: Timings Reset


Right now, the solution is to stay to the server release 1.20.1-41, until you implement a fix for this :)

**Comment by frogglen** [comment] 2023-06-26 04:49
same problem

**Comment by USBCharger** [comment] 2023-06-26 06:57
I just updated my server to 1.20.1 and am getting this issue, could you put out a hotfix A248?

**Comment by KoxSosen** [comment] 2023-06-26 09:18
I have temporary patched LibertyBans and MorePaperLib to fix this issue. You can get a temporary build [here](https://ci.hahota.net/job/Testing/job/LB-Unofficial/). However do note, that this build is **not** official and will be removed after an official fix is released. This issue will be updated when the official fix drops.

**Comment by USBCharger** [comment] 2023-06-26 10:26
> I just updated my server to 1.20.1 and am getting this issue, could you put out a hotfix A248?

Thanks Kox, however I just got finished going though a different route to fix the issue (I put libertybans on my proxy server)

Something that I wanted to note that I found in my testing:
While libertybans technically works on Build 39 (and therefore I'm assuming 41) if you restart the server, or reload libertybans, it will break as soon as it has to read the configuration files.

**Comment by Athar42** [comment] 2023-06-26 11:52
> 

That might be on your specific server.
Maybe some kind of plugin conflict, because in my case, using PaperMC build 41, I did a shutdown, backup then restart everydays, and it's still working.

**Comment by USBCharger** [comment] 2023-06-26 14:05
What I was trying to say was this was with the default configuration with libertybans. Plugin could start the first time, but after restarting or reloading, it would break trying to read it's own self-generated configuration.

The error:
`[07:53:38 INFO]: [LibertyBans] Enabling LibertyBans v1.1.0-M2
[07:53:38 INFO]: [LibertyBans] No addons detected
[07:53:39 INFO]: [space.arim.libertybans.core.addon.AddonLoader] No addons loaded
[07:53:40 INFO]: [space.arim.libertybans.core.AbstractBaseFoundation] Conducting start phase...
[07:53:40 ERROR]: Error occurred while enabling LibertyBans v1.1.0-M2 (Is it up to date?)
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
        at space.arim.dazzleconf.ext.snakeyaml.SnakeYamlOptions$Builder.lambda$new$0(SnakeYamlOptions.java:111) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.ext.snakeyaml.SnakeYamlConfigurationFactory.loadMapFromReader(SnakeYamlConfigurationFactory.java:131) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.factory.AbstractConfigurationFactory$ConfigFactoryDelegate.loadMap(AbstractConfigurationFactory.java:148) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.factory.HumanReadableConfigurationFactory.bufferedLoadMap(HumanReadableConfigurationFactory.java:90) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.factory.HumanReadableConfigurationFactory.loadMap(HumanReadableConfigurationFactory.java:78) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.factory.ConfigurationFormatFactory.load(ConfigurationFormatFactory.java:126) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.factory.DelegatingConfigurationFactory.load(DelegatingConfigurationFactory.java:57) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.factory.AbstractConfigurationFactory.load(AbstractConfigurationFactory.java:42) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.config.ConfigHolder.loadFromPath(ConfigHolder.java:116) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.config.ConfigHolder.lambda$reload$0(ConfigHolder.java:87) ~[LibertyBans-ClassLoader:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 6 more
[07:53:40 INFO]: [LibertyBans] Disabling LibertyBans v1.1.0-M2`

**Comment by Athar42** [comment] 2023-06-26 14:13
Try with the latest snapshot : https://ci.hahota.net/job/LibertyBans/
I think that's the reason of your error.

**Comment by KoxSosen** [comment] 2023-06-26 14:16
Yup, this issue was fixed in [a8cbe6d](https://github.com/A248/LibertyBans/commit/a8cbe6df5e43ff46947ad51cd623a212c18e7057), using a dev build will solve the issue. Do note that in order for LibertyBans to work on the latest Paper, you'll have to use a build mentioned in [this](https://github.com/A248/LibertyBans/issues/219#issuecomment-1607058129) reply.

**Comment by USBCharger** [comment] 2023-06-26 14:23
Oh, I had looked and saw that it failed to build, so I assumed I wouldn't be able to use it.

**Comment by pO7HncXR** [comment] 2023-07-06 04:29
`[07:26:55 INFO]: [LibertyBans] Enabling LibertyBans v1.1.0-SNAPSHOT-2023-06-16T16:27:42Z
[07:26:56 INFO]: [LibertyBans] No addons detected
[07:26:57 INFO]: [space.arim.libertybans.core.addon.AddonLoader] No addons loaded
[07:26:58 INFO]: [space.arim.libertybans.core.AbstractBaseFoundation] Conducting start phase...
[07:26:58 ERROR]: Error occurred while enabling LibertyBans v1.1.0-SNAPSHOT-2023-06-16T16:27:42Z (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.Server.isGlobalTickThread()'
        at space.arim.morepaperlib.scheduling.GracefulScheduling.isOnGlobalRegionThread(GracefulScheduling.java:146) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.isPrimaryThread0(BukkitFactoryOfTheFutureImpl.java:59) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.concurrent.MainThreadCachingFutureFactory.isPrimaryThread(MainThreadCachingFutureFactory.java:49) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.create(BukkitFactoryOfTheFutureImpl.java:53) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:56) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:45) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitPlatformHandleImpl.createFuturesFactory(BukkitPlatformHandle.java:61) ~[LibertyBans-ClassLoader:?]
        at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
        at space.arim.libertybans.core.service.StandardAsynchronicityManager.startup(StandardAsynchronicityManager.java:90) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.LifecycleGodfather.startup0(LifecycleGodfather.java:75) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.timedEvent(AbstractBaseFoundation.java:126) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.startup(AbstractBaseFoundation.java:64) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.env.spigot.plugin.SpigotPlugin.initialize(SpigotPlugin.java:116) ~[LibertyBans_1.1.0-SNAPSHOT.jar:?]
        at space.arim.libertybans.env.spigot.plugin.SpigotPlugin.onEnable(SpigotPlugin.java:48) ~[LibertyBans_1.1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[07:26:58 INFO]: [LibertyBans] Disabling LibertyBans v1.1.0-SNAPSHOT-2023-06-16T16:27:42Z`

**Comment by A248** [comment] 2023-07-08 08:29
'Official' development builds are now available from the CI website: https://ci.hahota.net/job/LibertyBans/.

A stable release will also be made available later today. This should assist anyone on shared hosting or otherwise unable to use development builds.

**Closed by A248** 2023-07-08 08:29 UTC
Labels: bug
