### ISSUE TITLE
problem with the essential

### ISSUE THREAD

**Issue by Z3r0xh** [A248/LibertyBans#271] opened 2024-07-08 05:09 UTC
### LibertyBans Version

LibertyBans 1.1.0-SNAPSHOT

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Spigot/Paper

### Description

When using essentialsX together with libertybans, commands like /ban, /mute /kick etc. do not work on the part of liberybans.

Even disabling the commands in the essentials file they still do not work, even if the commands.yml file is modified.

The solution I found was to eliminate these commands from the essentialsX plugin.yml.

For some reason the priority of libertbans is lower than that of essentials

**Comment by givinghawk** [comment] 2024-07-08 21:57
getting the same on 1.1.0-RC2

**Comment by KoxSosen** [comment] 2024-07-10 16:19
I believe this is a duplicate of #239. Please continue discussions regarding the matter on that issue. 

I know that A248 specially asked you to open this issue on Discord, but it's better to keep things organized, so they can be tracked as one issue instead of multiple. Thank you for the new workaround, and for reporting the issue!

**Closed** 2024-07-10 16:19 UTC
Labels: bug
